fix(lib/highlight): Ignore invalid highlight keys
nvimtools/hydra.nvim pull request #18
Opened 2023-12-31 14:44 UTC by Frederick888

If a user sets colour scheme to default after Neovim starts,
nvim_get_hl_by_name('HydraRed', true) returns { [true] = 6 }. This
causes an 'invalid key' error later when it's used in nvim_set_hl().

It is quite a rare case, and it should be fine as long as we can avoid
the error, so that Hydra still functions.

---

This was https://github.com/anuvyklack/hydra.nvim/pull/75

2023-12-31 19:27 UTC, benlubas approved these changes

2023-12-31 19:32 UTC, benlubas requested changes
could we switch to the new api function `nvim_get_hl`

2023-12-31 19:32 UTC, benlubas commented on lua/hydra/lib/highlight.lua
> +   for key, value in pairs(api.nvim_get_hl_by_name(name, rgb)) do
ah, wait, this is a deprecated api

2023-12-31 19:44 UTC, benlubas commented
@Frederick888 I'm unable to reproduce the issue as described in the original issue you linked, but I didn't have to do any of the key checks that you had to do (b/c we're using the new api)

Can you make sure that this branch works and then I can go ahead and merge this

2024-01-01 07:12 UTC, Frederick888 commented
@benlubas Yes, I can confirm this branch works. Thank you.

2024-01-01 16:25 UTC, benlubas approved these changes

2024-01-01 16:27 UTC, merged